<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "2_classes",
                     "development" => false,
                     "summary" => "Export of 2 content classes",
                     "description" => "This package contains exported definitions of the following content classes:\n- Contact\n- Objet contact\n",
                     "vendor" => false,
                     "vendor-dir" => "local",
                     "priority" => false,
                     "type" => "contentclass",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "Community Project 2012.6",
                                           "named-version" => "Community Project 2012.6" ),
                     "maintainers" => array( array( "name" => "Régent Gaëtan",
                                                    "email" => "gaetan.regent@maecia.com",
                                                    "role" => "developer" ) ),
                     "packaging" => array( "timestamp" => "1362503734",
                                           "host" => "show.staging.maecia.com",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1362503734",
                                                  "person" => "Régent Gaëtan",
                                                  "email" => "gaetan.regent@maecia.com",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array( array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "contact_form" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "object_contact" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezcontentclass",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "class-contact_form",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "type" => "ezcontentclass",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "class-object_contact",
                                                "sub-directory" => "ezcontentclass" ) ),
                     "uninstall" => array( array( "type" => "ezcontentclass",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "class-contact_form",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "type" => "ezcontentclass",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "class-object_contact",
                                                  "sub-directory" => "ezcontentclass" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/local";
?>
