<?php
/**
 * Autoloader definition for eZ Publish Extension files.
 *
 * @copyright Copyright (C) 1999-2012 eZ Systems AS. All rights reserved.
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
 * @version  2012.6
 * @package kernel
 *
 */

return array(
      'EnchantSpell'                        => 'extension/ezoe/modules/ezoe/classes/EnchantSpell.php',
      'GoogleSpell'                         => 'extension/ezoe/modules/ezoe/classes/GoogleSpell.php',
      'Moxiecode_JSON'                      => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'Moxiecode_JSONReader'                => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'PSpell'                              => 'extension/ezoe/modules/ezoe/classes/PSpell.php',
      'PSpellShell'                         => 'extension/ezoe/modules/ezoe/classes/PSpellShell.php',
      'SpellChecker'                        => 'extension/ezoe/modules/ezoe/classes/SpellChecker.php',
      'eZHTTPCacheManager'                  => 'extension/ezmodule/classes/ezhttpcachemanager.php',
      'eZIEEzcConversions'                  => 'extension/ezie/classes/interfaces/conversions.php',
      'eZIEEzcGDHandler'                    => 'extension/ezie/classes/handlers/gd.php',
      'eZIEEzcImageMagickHandler'           => 'extension/ezie/classes/handlers/magick.php',
      'eZIEImageAction'                     => 'extension/ezie/classes/image_action.php',
      'eZIEImageAnalyzer'                   => 'extension/ezie/classes/image_analyzer.php',
      'eZIEImageFilterBW'                   => 'extension/ezie/classes/image_filter_bw.php',
      'eZIEImageFilterBrightness'           => 'extension/ezie/classes/image_filter_brightness.php',
      'eZIEImageFilterContrast'             => 'extension/ezie/classes/image_filter_contrast.php',
      'eZIEImageFilterSepia'                => 'extension/ezie/classes/image_filter_sepia.php',
      'eZIEImagePreAction'                  => 'extension/ezie/classes/image_pre_action.php',
      'eZIEImageToolCrop'                   => 'extension/ezie/classes/image_tool_crop.php',
      'eZIEImageToolFlipHorizontally'       => 'extension/ezie/classes/image_tool_flip_horizontally.php',
      'eZIEImageToolFlipVertically'         => 'extension/ezie/classes/image_tool_flip_vertically.php',
      'eZIEImageToolPixelate'               => 'extension/ezie/classes/image_tool_pixelate.php',
      'eZIEImageToolResize'                 => 'extension/ezie/classes/image_tool_resize.php',
      'eZIEImageToolRotation'               => 'extension/ezie/classes/image_tool_rotation.php',
      'eZIEImageToolWatermark'              => 'extension/ezie/classes/image_tool_watermark.php',
      'eZIEezcImageConverter'               => 'extension/ezie/classes/image_converter.php',
      'eZJSON'                              => 'extension/ezmodule/autoloads/ezjson.php',
      'eZModuleAjaxContent'                 => 'extension/ezmodule/classes/ezmoduleajaxcontent.php',
      'eZModuleBlock'                       => 'extension/ezmodule/classes/ezmoduleblock.php',
      'eZModuleFunctionCollection'          => 'extension/ezmodule/modules/ezmodule/functioncollection.php',
      'eZModuleServerCallFunctions'         => 'extension/ezmodule/classes/ezmoduleservercallfunctions.php',
      'eZMultiuploadHandler'                => 'extension/ezmultiupload/classes/ezmultiuploadhandler.php',
      'eZMultiuploadHandlerInterface'       => 'extension/ezmultiupload/classes/ezmultiuploadhandlerinterface.php',
      'eZOEInputParser'                     => 'extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php',
      'eZOETemplateUtils'                   => 'extension/ezoe/autoloads/ezoetemplateutils.php',
      'eZOEXMLInput'                        => 'extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php',
      'eZOOConverter'                       => 'extension/ezodf/classes/ezooconverter.php',
      'eZOOGenerator'                       => 'extension/ezodf/classes/ezoogenerator.php',
      'eZOOImport'                          => 'extension/ezodf/classes/ezooimport.php',
      'eZOpenofficeUploadHandler'           => 'extension/ezodf/uploadhandlers/ezopenofficeuploadhandler.php',
      'eZPage'                              => 'extension/ezmodule/classes/ezpage.php',
      'eZPageBlock'                         => 'extension/ezmodule/classes/ezpageblock.php',
      'eZPageType'                          => 'extension/ezmodule/datatypes/ezpage/ezpagetype.php',
      'eZPageZone'                          => 'extension/ezmodule/classes/ezpagezone.php',
      'eZRESTODFHandler'                    => 'extension/ezodf/classes/ezrestodfhandler.php',
      'eZTags'                              => 'extension/eztags/datatypes/eztags/eztags.php',
      'eZTagsAttributeFilter'               => 'extension/eztags/classes/eztagsattributefilter.php',
      'eZTagsAttributeLinkObject'           => 'extension/eztags/classes/eztagsattributelinkobject.php',
      'eZTagsCloud'                         => 'extension/eztags/autoloads/eztagscloud.php',
      'eZTagsFunctionCollection'            => 'extension/eztags/modules/tags/eztagsfunctioncollection.php',
      'eZTagsObject'                        => 'extension/eztags/classes/eztagsobject.php',
      'eZTagsTemplateFunctions'             => 'extension/eztags/autoloads/eztagstemplatefunctions.php',
      'eZTagsType'                          => 'extension/eztags/datatypes/eztags/eztagstype.php',
      'eZUnserialize'                       => 'extension/ezmodule/autoloads/ezunserialize.php',
      'ezCDNClass'                          => 'extension/ezutils/classes/ez_cdn.php',
      'ezOperators'                         => 'extension/ezutils/classes/ez_operators.php',
      'ezVideo'                             => 'extension/ezutils/classes/ez_video.php',
      'ezjscAccessTemplateFunctions'        => 'extension/ezjscore/autoloads/ezjscaccesstemplatefunctions.php',
      'ezjscAjaxContent'                    => 'extension/ezjscore/classes/ezjscajaxcontent.php',
      'ezjscCssOptimizer'                   => 'extension/ezjscore/classes/ezjsccssoptimizer.php',
      'ezjscEncodingTemplateFunctions'      => 'extension/ezjscore/autoloads/ezjscencodingtemplatefunctions.php',
      'ezjscJavascriptOptimizer'            => 'extension/ezjscore/classes/ezjscjavascriptoptimizer.php',
      'ezjscPacker'                         => 'extension/ezjscore/classes/ezjscpacker.php',
      'ezjscPackerTemplateFunctions'        => 'extension/ezjscore/autoloads/ezjscpackertemplatefunctions.php',
      'ezjscServerFunctions'                => 'extension/ezjscore/classes/ezjscserverfunctions.php',
      'ezjscServerFunctionsAjaxUploader'    => 'extension/ezjscore/classes/ezjscserverfunctionsajaxuploader.php',
      'ezjscServerFunctionsAutosave'        => 'extension/ezautosave/classes/ezjscserverfunctionsautosave.php',
      'ezjscServerFunctionsJs'              => 'extension/ezjscore/classes/ezjscserverfunctionsjs.php',
      'ezjscServerFunctionsNode'            => 'extension/ezjscore/classes/ezjscserverfunctionsnode.php',
      'ezjscServerFunctionsPublishingQueue' => 'extension/ezjscore/classes/ezjscserverfunctionspublishingqueue.php',
      'ezjscServerRouter'                   => 'extension/ezjscore/classes/ezjscserverrouter.php',
      'ezjscoreTagsSuggest'                 => 'extension/eztags/classes/ezjscoretagssuggest.php',
      'ezmultiuploadInfo'                   => 'extension/ezmultiupload/ezinfo.php',
      'ezodfInfo'                           => 'extension/ezodf/ezinfo.php',
      'ezoeServerFunctions'                 => 'extension/ezoe/classes/ezoeserverfunctions.php',
      'ezpAjaxUploaderHandlerInterface'     => 'extension/ezjscore/classes/ajaxuploader/ezpajaxuploaderhandlerinterface.php',
      'ezpRelationAjaxUploader'             => 'extension/ezjscore/classes/ajaxuploader/ezprelationajaxuploader.php',
      'ezpRelationListAjaxUploader'         => 'extension/ezjscore/classes/ajaxuploader/ezprelationlistajaxuploader.php',
      'eztagsInfo'                          => 'extension/eztags/ezinfo.php',
    );

?>
