<?php /* #?ini charset="utf-8"?
[EditorLayout]
Buttons[]
Buttons[]=formatselect
Buttons[]=|
Buttons[]=bold
Buttons[]=italic
Buttons[]=underline
Buttons[]=|
Buttons[]=sub
Buttons[]=sup
Buttons[]=|
Buttons[]=justifyleft
Buttons[]=justifycenter
Buttons[]=justifyright
Buttons[]=justifyfull
Buttons[]=|
Buttons[]=bullist
Buttons[]=numlist
Buttons[]=indent
Buttons[]=outdent
Buttons[]=|
Buttons[]=undo
Buttons[]=redo
Buttons[]=|
Buttons[]=link
Buttons[]=unlink
Buttons[]=anchor
Buttons[]=|
Buttons[]=image
Buttons[]=object
Buttons[]=custom
Buttons[]=|
Buttons[]=literal
Buttons[]=charmap
Buttons[]=|
Buttons[]=table
Buttons[]=delete_table
Buttons[]=delete_col
Buttons[]=col_after
Buttons[]=delete_row
Buttons[]=row_after
Buttons[]=split_cells
Buttons[]=merge_cells
Buttons[]=|
Buttons[]=fullscreen

[EditorLayout_mini]
Buttons[]
Buttons[]=bold
Buttons[]=italic
Buttons[]=underline
Buttons[]=|
Buttons[]=undo
Buttons[]=redo
PathLocation=none

*/ ?>
